### ISSUE TITLE
afcomp crashes if there is byebug

### ISSUE THREAD

**Issue by kirillrdy** [cjheath/activefacts-compositions#13]
Steps to reproduce
`afgen # in enviroment with no byebug installed`

```
LoadError: cannot load such file -- byebug
  /kita/world/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/activefacts-compositions-1.9.18/lib/activefacts/generator/doc/glossary.rb:11:in `require'
  /kita/world/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/activefacts-compositions-1.9.18/lib/activefacts/generator/doc/glossary.rb:11:in `<top (required)>'
  /kita/world/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/activefacts-compositions-1.9.18/bin/afcomp:41:in `require'
  /kita/world/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/activefacts-compositions-1.9.18/bin/afcomp:41:in `block (2 levels) in enumerate_available'
  /kita/world/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/activefacts-compositions-1.9.18/bin/afcomp:39:in `select'
  /kita/world/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/activefacts-compositions-1.9.18/bin/afcomp:39:in `block in enumerate_available'
  /kita/world/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/tracing-2.0.8/lib/tracing.rb:292:in `trace'
  /kita/world/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/activefacts-compositions-1.9.18/bin/afcomp:36:in `enumerate_available'
  /kita/world/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/activefacts-compositions-1.9.18/bin/afcomp:183:in `<top (required)>'
  /kita/world/ruby-2.5.0/lib/ruby/gems/2.5.0/bin/afcomp:23:in `load'
  /kita/world/ruby-2.5.0/lib/ruby/gems/2.5.0/bin/afcomp:23:in `<top (required)>'

```

its a trivial fix, but I've noticed that glossary generator requires byebug, but its never listed as a dependecy.

Further more there are 2 references to "debugger" in code also with no mention of which debugger is being used

**Comment by cjheath** [comment]
Removed from glossary.rb. It was never needed anyhow; you can load a debugger using TRACE=debug via the tracing gem. This also aliases the "byebug" method to "debugger", so that the debugger call in generator/validate works (this is only called if you enable composition_validator_debug tracing, so you know what you're doing).

**Comment by cjheath** [comment]
Checking other gems, there are one or two slips, but most calls are deliberate, in code that's incomplete or hopelessly faulty, or under control of a trace call.
