### ISSUE TITLE
Generation failed for provided sample

### ISSUE THREAD

**Issue by DanielHeath** [cjheath/activefacts-compositions#16]
My repo: https://gist.github.com/DanielHeath/eba77378b400ebc876e24625e0c661cf

This contains the latest released version of activefacts-compositions and dependencies, and the CinemaTickets model.

```
  $ schema_compositor --binary --rails/models CinemaTickets.cql
gems/activefacts-compositions-1.9.19/lib/activefacts/generator/rails/models.rb:129:in `model_key': undefined method `all_index_field' for nil:NilClass (NoMethodError)
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/rails/models.rb:143:in `model_body'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/rails/models.rb:106:in `generate_composite'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/rails/models.rb:47:in `block in generate'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/rails/models.rb:47:in `map'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/rails/models.rb:47:in `generate'
  from gems/activefacts-compositions-1.9.19/bin/schema_compositor:129:in `block (2 levels) in process_files'
  from gems/activefacts-compositions-1.9.19/bin/schema_compositor:128:in `each'
  from gems/activefacts-compositions-1.9.19/bin/schema_compositor:128:in `block in process_files'
  from gems/activefacts-compositions-1.9.19/bin/schema_compositor:85:in `each'
  from gems/activefacts-compositions-1.9.19/bin/schema_compositor:85:in `process_files'
  from gems/activefacts-compositions-1.9.19/bin/schema_compositor:195:in `<top (required)>'
  from bin/schema_compositor:23:in `load'
  from bin/schema_compositor:23:in `<main>'
```

**Comment by DanielHeath** [comment]
Similarly:
```
  $ schema_compositor --relational --ruby CinemaTickets.cql
gems/activefacts-compositions-1.9.19/lib/activefacts/generator/oo.rb:144:in `block (2 levels) in generate_class': undefined method `mapping' for nil:NilClass (NoMethodError)
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/oo.rb:144:in `each'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/oo.rb:144:in `detect'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/oo.rb:144:in `block in generate_class'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/oo.rb:144:in `reject'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/oo.rb:144:in `generate_class'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/oo.rb:148:in `block in generate_class'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/oo.rb:148:in `map'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/oo.rb:148:in `generate_class'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/oo.rb:46:in `block in generate_classes'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/oo.rb:45:in `map'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/oo.rb:45:in `generate_classes'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/ruby.rb:41:in `generate_classes'
  from gems/activefacts-compositions-1.9.19/lib/activefacts/generator/oo.rb:39:in `generate'
  from gems/activefacts-compositions-1.9.19/bin/schema_compositor:129:in `block (2 levels) in process_files'
  from gems/activefacts-compositions-1.9.19/bin/schema_compositor:128:in `each'
  from gems/activefacts-compositions-1.9.19/bin/schema_compositor:128:in `block in process_files'
  from gems/activefacts-compositions-1.9.19/bin/schema_compositor:85:in `each'
  from gems/activefacts-compositions-1.9.19/bin/schema_compositor:85:in `process_files'
  from gems/activefacts-compositions-1.9.19/bin/schema_compositor:195:in `<top (required)>'
  from bin/schema_compositor:23:in `load'
  from bin/schema_compositor:23:in `<main>'
```

**Comment by cjheath** [comment]
Some generators require particular compositors, but there is no internal representation of this dependency. I think there needs to be explicit dependencies that show up in --help

**Comment by cjheath** [comment]
The help text now indicates which compositors to use in each case.
